package View;

import Controller.TarefaControle;
import Model.Projeto;
import Model.Tarefa;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author devpovoa
 */
public class CadastroTafera extends javax.swing.JDialog {

    TarefaControle controle;
    Projeto projeto;

    /**
     * Creates new form CadastroTafera
     *
     * @param parent
     * @param modal
     */
    public CadastroTafera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controle = new TarefaControle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTaferaPrincipal = new javax.swing.JPanel();
        layoutTarefa = new javax.swing.JLabel();
        imgLayoutTarefa = new javax.swing.JLabel();
        painelTarefaUtilidade = new javax.swing.JPanel();
        nomeTarefa = new javax.swing.JLabel();
        inputNomeTarefa = new javax.swing.JTextField();
        descricaoTarefa = new javax.swing.JLabel();
        scrollPainelDescricao = new javax.swing.JScrollPane();
        inputDescricaoTarefa = new javax.swing.JTextArea();
        prazoTarefa = new javax.swing.JLabel();
        inputPrazoTarefa = new javax.swing.JFormattedTextField();
        notasTarefa = new javax.swing.JLabel();
        scrollPainelNotas = new javax.swing.JScrollPane();
        inputNotasTarefa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 495));

        painelTaferaPrincipal.setBackground(new java.awt.Color(0, 153, 102));

        layoutTarefa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        layoutTarefa.setForeground(new java.awt.Color(255, 255, 255));
        layoutTarefa.setText("Tarefa");

        imgLayoutTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLayoutTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        imgLayoutTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLayoutTarefaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelTaferaPrincipalLayout = new javax.swing.GroupLayout(painelTaferaPrincipal);
        painelTaferaPrincipal.setLayout(painelTaferaPrincipalLayout);
        painelTaferaPrincipalLayout.setHorizontalGroup(
            painelTaferaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTaferaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layoutTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(imgLayoutTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelTaferaPrincipalLayout.setVerticalGroup(
            painelTaferaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTaferaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTaferaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layoutTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgLayoutTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelTarefaUtilidade.setBackground(new java.awt.Color(255, 255, 255));

        nomeTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeTarefa.setText("Nome");

        inputNomeTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        descricaoTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descricaoTarefa.setText("Descrição");

        inputDescricaoTarefa.setColumns(20);
        inputDescricaoTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputDescricaoTarefa.setRows(5);
        scrollPainelDescricao.setViewportView(inputDescricaoTarefa);

        prazoTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prazoTarefa.setText("Prazo");

        inputPrazoTarefa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        notasTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notasTarefa.setText("Notas");

        inputNotasTarefa.setColumns(20);
        inputNotasTarefa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNotasTarefa.setRows(5);
        scrollPainelNotas.setViewportView(inputNotasTarefa);

        javax.swing.GroupLayout painelTarefaUtilidadeLayout = new javax.swing.GroupLayout(painelTarefaUtilidade);
        painelTarefaUtilidade.setLayout(painelTarefaUtilidadeLayout);
        painelTarefaUtilidadeLayout.setHorizontalGroup(
            painelTarefaUtilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTarefaUtilidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTarefaUtilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPainelDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descricaoTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNomeTarefa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prazoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPrazoTarefa)
                    .addComponent(notasTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPainelNotas))
                .addContainerGap())
        );
        painelTarefaUtilidadeLayout.setVerticalGroup(
            painelTarefaUtilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTarefaUtilidadeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nomeTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomeTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descricaoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPainelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prazoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPrazoTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notasTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPainelNotas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTaferaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTarefaUtilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTaferaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTarefaUtilidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgLayoutTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLayoutTarefaMouseClicked
        // TODO add your handling code here:
        try {

            if (inputNomeTarefa.getText().isEmpty() || inputPrazoTarefa.getText().isEmpty()) {

                JOptionPane.showMessageDialog(rootPane, "Tarefa não pode ser salva por falta"
                        + " de nome ou prazo.");
            } else {
                Tarefa tarefa = new Tarefa();

                tarefa.setIdProject(projeto.getId());

                tarefa.setNome(inputNomeTarefa.getText());
                tarefa.setDescricao(inputDescricaoTarefa.getText());
                tarefa.setObservacao(inputNotasTarefa.getText());
                tarefa.setSituacao(false);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date data = null;
                data = dateFormat.parse(inputPrazoTarefa.getText());
                tarefa.setPrazo(data);

                controle.salvar(tarefa);
                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!");
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(CadastroTafera.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_imgLayoutTarefaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTafera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            CadastroTafera dialog = new CadastroTafera(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descricaoTarefa;
    private javax.swing.JLabel imgLayoutTarefa;
    private javax.swing.JTextArea inputDescricaoTarefa;
    private javax.swing.JTextField inputNomeTarefa;
    private javax.swing.JTextArea inputNotasTarefa;
    private javax.swing.JFormattedTextField inputPrazoTarefa;
    private javax.swing.JLabel layoutTarefa;
    private javax.swing.JLabel nomeTarefa;
    private javax.swing.JLabel notasTarefa;
    private javax.swing.JPanel painelTaferaPrincipal;
    private javax.swing.JPanel painelTarefaUtilidade;
    private javax.swing.JLabel prazoTarefa;
    private javax.swing.JScrollPane scrollPainelDescricao;
    private javax.swing.JScrollPane scrollPainelNotas;
    // End of variables declaration//GEN-END:variables

    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

}
