package View;

import Controller.ProjetoControle;
import Controller.TarefaControle;
import Model.Projeto;
import Model.Tarefa;
import Util.ColunaDePrazoRendenizada;
import Util.RendenizaButoes;
import Util.TabelaTarefaModelo;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author devpovoa
 */
public final class TelaPrincipal extends javax.swing.JFrame {

    ProjetoControle projetoControle;
    TarefaControle tarefaControle;

    DefaultListModel projetoModelo;
    TabelaTarefaModelo tarefaModelo;

    public TelaPrincipal() {
        initComponents();
        iniciaDataControle();
        iniciaComponetesModelo();
        decoracaoTabelaTarefas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divVisualTarefaCheia = new javax.swing.JScrollPane();
        listTabelaTarefas = new javax.swing.JTable();
        canvas = new javax.swing.JPanel();
        divLayout = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        subTituloPrincipal = new javax.swing.JLabel();
        divProjetos = new javax.swing.JPanel();
        tituloProjeto = new javax.swing.JLabel();
        imgProjeto = new javax.swing.JLabel();
        divTarefas = new javax.swing.JPanel();
        tituloTarefa = new javax.swing.JLabel();
        imgTarefa = new javax.swing.JLabel();
        divLista = new javax.swing.JPanel();
        listDeItens = new javax.swing.JScrollPane();
        itens = new javax.swing.JList<>();
        containerTarefa = new javax.swing.JPanel();
        divVisualTarefaVazia = new javax.swing.JPanel();
        logoTarefa = new javax.swing.JLabel();
        msnTarefa = new javax.swing.JLabel();
        infoTarefa = new javax.swing.JLabel();

        listTabelaTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listTabelaTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTabelaTarefas.setGridColor(new java.awt.Color(255, 255, 255));
        listTabelaTarefas.setRowHeight(50);
        listTabelaTarefas.setSelectionBackground(new java.awt.Color(102, 255, 102));
        listTabelaTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTabelaTarefas.setShowHorizontalLines(true);
        listTabelaTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTabelaTarefasMouseClicked(evt);
            }
        });
        divVisualTarefaCheia.setViewportView(listTabelaTarefas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        canvas.setBackground(new java.awt.Color(204, 204, 204));

        divLayout.setBackground(new java.awt.Color(0, 153, 102));

        tituloPrincipal.setBackground(new java.awt.Color(0, 153, 102));
        tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tituloPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        tituloPrincipal.setText(" My App");

        subTituloPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        subTituloPrincipal.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout divLayoutLayout = new javax.swing.GroupLayout(divLayout);
        divLayout.setLayout(divLayoutLayout);
        divLayoutLayout.setHorizontalGroup(
            divLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        divLayoutLayout.setVerticalGroup(
            divLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divLayoutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subTituloPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        divProjetos.setBackground(new java.awt.Color(255, 255, 255));
        divProjetos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tituloProjeto.setBackground(new java.awt.Color(255, 255, 255));
        tituloProjeto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloProjeto.setForeground(new java.awt.Color(0, 153, 102));
        tituloProjeto.setText("Projetos");

        imgProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        imgProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout divProjetosLayout = new javax.swing.GroupLayout(divProjetos);
        divProjetos.setLayout(divProjetosLayout);
        divProjetosLayout.setHorizontalGroup(
            divProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgProjeto)
                .addContainerGap())
        );
        divProjetosLayout.setVerticalGroup(
            divProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        divTarefas.setBackground(new java.awt.Color(255, 255, 255));
        divTarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tituloTarefa.setBackground(new java.awt.Color(255, 255, 255));
        tituloTarefa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloTarefa.setForeground(new java.awt.Color(0, 153, 102));
        tituloTarefa.setText("Tarefas");

        imgTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        imgTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTarefaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout divTarefasLayout = new javax.swing.GroupLayout(divTarefas);
        divTarefas.setLayout(divTarefasLayout);
        divTarefasLayout.setHorizontalGroup(
            divTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(imgTarefa)
                .addContainerGap())
        );
        divTarefasLayout.setVerticalGroup(
            divTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        divLista.setBackground(new java.awt.Color(255, 255, 255));
        divLista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        itens.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        itens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        itens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itens.setFixedCellHeight(50);
        itens.setSelectionBackground(new java.awt.Color(0, 153, 102));
        itens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itensMouseClicked(evt);
            }
        });
        listDeItens.setViewportView(itens);

        javax.swing.GroupLayout divListaLayout = new javax.swing.GroupLayout(divLista);
        divLista.setLayout(divListaLayout);
        divListaLayout.setHorizontalGroup(
            divListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listDeItens)
                .addContainerGap())
        );
        divListaLayout.setVerticalGroup(
            divListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listDeItens, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerTarefa.setBackground(new java.awt.Color(255, 255, 255));
        containerTarefa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        containerTarefa.setLayout(new java.awt.BorderLayout());

        divVisualTarefaVazia.setBackground(new java.awt.Color(255, 255, 255));
        divVisualTarefaVazia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoTarefa.setBackground(new java.awt.Color(255, 255, 255));
        logoTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        msnTarefa.setBackground(new java.awt.Color(255, 255, 255));
        msnTarefa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        msnTarefa.setForeground(new java.awt.Color(0, 153, 102));
        msnTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msnTarefa.setText("Nenhuma tarefa por aqui ;D");

        infoTarefa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infoTarefa.setForeground(new java.awt.Color(102, 102, 102));
        infoTarefa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoTarefa.setText("Clique no botão \" + \" para adicionar uma nova tarefa");

        javax.swing.GroupLayout divVisualTarefaVaziaLayout = new javax.swing.GroupLayout(divVisualTarefaVazia);
        divVisualTarefaVazia.setLayout(divVisualTarefaVaziaLayout);
        divVisualTarefaVaziaLayout.setHorizontalGroup(
            divVisualTarefaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divVisualTarefaVaziaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divVisualTarefaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(msnTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
        );
        divVisualTarefaVaziaLayout.setVerticalGroup(
            divVisualTarefaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divVisualTarefaVaziaLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(logoTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msnTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoTarefa)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        containerTarefa.add(divVisualTarefaVazia, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(canvasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(divProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canvasLayout.createSequentialGroup()
                .addComponent(divLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgProjetoMouseClicked
        // TODO add your handling code here:
        CadastroProjeto cadastroProjeto = new CadastroProjeto(this, rootPaneCheckingEnabled);
        cadastroProjeto.setVisible(true);

        cadastroProjeto.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                carregaProjeto();
            }
        });
    }//GEN-LAST:event_imgProjetoMouseClicked

    private void imgTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTarefaMouseClicked
        // TODO add your handling code here:
        CadastroTafera cadastroTafera = new CadastroTafera(this, rootPaneCheckingEnabled);
        int projetoIndex = itens.getSelectedIndex();
        Projeto projeto = (Projeto) projetoModelo.get(projetoIndex);
        cadastroTafera.setProjeto(projeto);
        cadastroTafera.setVisible(true);

        cadastroTafera.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                carregaTarefa(projeto.getId());
            }
        });
    }//GEN-LAST:event_imgTarefaMouseClicked

    private void listTabelaTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTabelaTarefasMouseClicked
        // TODO add your handling code here:
        int linha = listTabelaTarefas.rowAtPoint(evt.getPoint());
        int coluna = listTabelaTarefas.columnAtPoint(evt.getPoint());

        Tarefa tarefa = tarefaModelo.getTarefa().get(linha);

        switch (coluna) {
            case 3 -> {

                tarefaControle.atualizar(tarefa);
            }
            case 5 -> {

                tarefaControle.removerId(tarefa.getId());
                tarefaModelo.getTarefa().remove(linha);

                int projetoIndex = itens.getSelectedIndex();
                Projeto projeto = (Projeto) projetoModelo.get(projetoIndex);
                carregaTarefa(projeto.getId());
            }
        }
    }//GEN-LAST:event_listTabelaTarefasMouseClicked

    private void itensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itensMouseClicked
        // TODO add your handling code here:
        int projetoIndex = itens.getSelectedIndex();
        Projeto projeto = (Projeto) projetoModelo.get(projetoIndex);
        carregaTarefa(projeto.getId());
    }//GEN-LAST:event_itensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvas;
    private javax.swing.JPanel containerTarefa;
    private javax.swing.JPanel divLayout;
    private javax.swing.JPanel divLista;
    private javax.swing.JPanel divProjetos;
    private javax.swing.JPanel divTarefas;
    private javax.swing.JScrollPane divVisualTarefaCheia;
    private javax.swing.JPanel divVisualTarefaVazia;
    private javax.swing.JLabel imgProjeto;
    private javax.swing.JLabel imgTarefa;
    private javax.swing.JLabel infoTarefa;
    private javax.swing.JList<String> itens;
    private javax.swing.JScrollPane listDeItens;
    private javax.swing.JTable listTabelaTarefas;
    private javax.swing.JLabel logoTarefa;
    private javax.swing.JLabel msnTarefa;
    private javax.swing.JLabel subTituloPrincipal;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JLabel tituloProjeto;
    private javax.swing.JLabel tituloTarefa;
    // End of variables declaration//GEN-END:variables

    public void decoracaoTabelaTarefas() {

        listTabelaTarefas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        listTabelaTarefas.getTableHeader().setBackground(new Color(0, 153, 102));
        listTabelaTarefas.getTableHeader().setForeground(new Color(255, 255, 255));

        //istTabelaTarefas.setAutoCreateRowSorter(true);
        listTabelaTarefas.getColumnModel().getColumn(2).setCellRenderer(new ColunaDePrazoRendenizada());
        listTabelaTarefas.getColumnModel().getColumn(4).setCellRenderer(new RendenizaButoes("edit"));
        listTabelaTarefas.getColumnModel().getColumn(5).setCellRenderer(new RendenizaButoes("delete"));
    }

    public void iniciaDataControle() {
        projetoControle = new ProjetoControle();
        tarefaControle = new TarefaControle();
    }

    public void iniciaComponetesModelo() {
        projetoModelo = new DefaultListModel();
        carregaProjeto();

        tarefaModelo = new TabelaTarefaModelo();
        listTabelaTarefas.setModel(tarefaModelo);

        if (!projetoModelo.isEmpty()) {
            itens.setSelectedIndex(0);
            Projeto projeto = (Projeto) projetoModelo.get(0);
            carregaTarefa(projeto.getId());
        }

    }

    public void carregaTarefa(int idProjeto) {
        List<Tarefa> tarefas = tarefaControle.getAll(idProjeto);
        tarefaModelo.setTarefa(tarefas);

        showTabelaTarefa(!tarefas.isEmpty());
    }

    private void showTabelaTarefa(boolean exibiTarefa) {
        if (exibiTarefa) {
            if (divVisualTarefaVazia.isVisible()) {
                divVisualTarefaVazia.setVisible(false);
                containerTarefa.remove(divVisualTarefaVazia);
            }

            containerTarefa.add(divVisualTarefaCheia);
            divVisualTarefaCheia.setVisible(true);
            divVisualTarefaCheia.setSize(containerTarefa.getWidth(), containerTarefa.getHeight());
        } else {
            if (divVisualTarefaCheia.isVisible()) {
                divVisualTarefaCheia.setVisible(false);
                containerTarefa.remove(divVisualTarefaCheia);
            }

            containerTarefa.add(divVisualTarefaVazia);
            divVisualTarefaVazia.setVisible(true);
            divVisualTarefaVazia.setSize(containerTarefa.getWidth(), containerTarefa.getHeight());
        }
    }

    public void carregaProjeto() {

        List<Projeto> projetos = projetoControle.getAll();

        projetoModelo.clear();

        for (int i = 0; i < projetos.size(); i++) {

            Projeto projeto = projetos.get(i);
            projetoModelo.addElement(projeto);
        }
        itens.setModel(projetoModelo);
    }
}
